### HogangYes API 테스트

### 메인 페이지
GET {{baseUrl}}

### 부동산 검색: QueryParam: searchKey - name, searchValue - 강변힐스테이트
GET {{baseUrl}}/realestate?searchKey=name&searchValue=강변힐스테이트
# 20240801 소요시간: 2분 39초

### 부동산 검색: QueryParam: searchKey - beopJeongDong, searchValue - 염창동
GET {{baseUrl}}/realestate?searchKey=beopJeongDong&searchValue=염창동

### 부동산 검색: QueryParam: searchKey - realEstateType, searchValue - APT_RENT
GET {{baseUrl}}/realestate?searchKey=realEstateType&searchValue=APT_RENT

### 부동산 상세 정보 조회: queryParam: id - 1234432
GET {{baseUrl}}/realestate/detail?id=1234432

### 부동산 전월세 상세 정보 조회: queryParam: id - 1234432
GET {{baseUrl}}/realestate/rent?id=1234432

### 부동산 매매 상세 정보 조회: queryParam: id - 10649088
GET {{baseUrl}}/realestate/sale?id=10649088