### HogangYes API 테스트

### 메인 페이지
GET http://localhost:8080

### 부동산 검색: QueryParam: searchKey - name, searchValue - 강변힐스테이트아파트
GET http://localhost:8080/realestate?searchKey=name&searchValue=강변힐스테이트아파트

### 부동산 검색: QueryParam: searchKey - beopJeongDong, searchValue - 염창동
GET http://localhost:8080/realestate?searchKey=beopJeongDong&searchValue=염창동

### 부동산 검색: QueryParam: searchKey - realEstateType, searchValue - APT_RENT
GET http://localhost:8080/realestate?searchKey=realEstateType&searchValue=APT_RENT

### 부동산 상세 정보 조회: queryParam: id - 1
GET http://localhost:8080/realestate/detail?id=1